export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'